CREATE DATABASE WEB_19100158;

USE WEB_19100158;

CREATE TABLE MUSICA
(
ID SMALLINT AUTO_INCREMENT,
NOMBRE VARCHAR(100),
NACIONALIDAD VARCHAR(50),
FECHA_NACIMIENTO DATE,
DESCRIPCION VARCHAR(50),
ALBUM VARCHAR(50),
FECHA_PUBLICACION DATE,
CANCION VARCHAR(50),
DURACION VARCHAR(5),
CONSTRAINT PK_MUSICA PRIMARY KEY(ID)
);

INSERT INTO musica (NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, DESCRIPCION, ALBUM, FECHA_PUBLICACION,
CANCION, DURACION)
VALUES ('José Madero','Mexicana','1980-09-01','Cantate, compositor, escritor','Psalmos','2019-09-06','SSDD','3:32');

INSERT INTO musica (NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, DESCRIPCION, ALBUM, FECHA_PUBLICACION,
CANCION, DURACION)
VALUES ('Shawn Mendes','Canadiense','1998-08-08','Cantate, compositor'
,'Wonder','2020-12-04','305','3:09');